# Generated by Django 6.1.1 on 2026-09-28 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("tickets_for_sale", models.PositiveIntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_zones",
                        to="events.event",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_zones",
                        to="events.zone",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)),
                        name="check_event_zone_price_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tickets_for_sale__gt", 0)),
                        name="check_event_zone_tickets_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("event", "zone"), name="unique_zone_per_event"
                    ),
                ],
            },
        ),
    ]
