# Generated by Django 6.1.1 on 2026-09-28 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventzone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="event",
            name="check_event_ends_after_starts",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="check_event_ends_after_starts",
                violation_error_message="The event must end after it starts.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="eventzone",
            name="check_event_zone_price_non_negative",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)),
                name="check_event_zone_price_non_negative",
                violation_error_message="Price cannot be negative.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="eventzone",
            name="check_event_zone_tickets_positive",
            constraint=models.CheckConstraint(
                condition=models.Q(("tickets_for_sale__gt", 0)),
                name="check_event_zone_tickets_positive",
                violation_error_message="Tickets for sale must be greater than 0.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="zone",
            name="check_zone_capacity_positive",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gt", 0)),
                name="check_zone_capacity_positive",
                violation_error_message="Capacity must be greater than 0.",
            ),
        ),
    ]
