"""add buyer_email to reservation

Revision ID: c72b354cd30c
Revises: d10e9c9ca4af
Create Date: 2026-10-06 09:12:16.849317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72b354cd30c'
down_revision: Union[str, Sequence[str], None] = 'd10e9c9ca4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('buyer_email', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'buyer_email')
    # ### end Alembic commands ###
