"""add on_sale and catalog_event

Revision ID: d10e9c9ca4af
Revises: fee82f2ee486
Create Date: 2026-10-06 08:56:28.769855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10e9c9ca4af'
down_revision: Union[str, Sequence[str], None] = 'fee82f2ee486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_event',
    sa.Column('event_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_catalog_event'))
    )
    op.add_column('inventory', sa.Column('on_sale', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'on_sale')
    op.drop_table('catalog_event')
    # ### end Alembic commands ###
