"""add payment fields and processed stripe events

Revision ID: 6448ae8aac83
Revises: c72b354cd30c
Create Date: 2026-10-06 09:28:34.155098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6448ae8aac83'
down_revision: Union[str, Sequence[str], None] = 'c72b354cd30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_stripe_event',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_stripe_event'))
    )
    op.add_column('reservation', sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True))
    op.add_column('reservation', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('reservation', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reservation', sa.Column('tickets_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reservation', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reservation', sa.Column('stripe_refund_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'stripe_refund_id')
    op.drop_column('reservation', 'refunded_at')
    op.drop_column('reservation', 'tickets_sent_at')
    op.drop_column('reservation', 'paid_at')
    op.drop_column('reservation', 'stripe_payment_intent_id')
    op.drop_column('reservation', 'stripe_checkout_session_id')
    op.drop_table('processed_stripe_event')
    # ### end Alembic commands ###
