"""create inventory and reservation

Revision ID: fee82f2ee486
Revises:
Create Date: 2026-10-05 10:27:40.880260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee82f2ee486'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_zone_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available <= total', name=op.f('ck_inventory_available_le_total')),
    sa.CheckConstraint('available >= 0', name=op.f('ck_inventory_available_non_negative')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_inventory_price_non_negative')),
    sa.CheckConstraint('total > 0', name=op.f('ck_inventory_total_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory')),
    sa.UniqueConstraint('event_zone_id', name=op.f('uq_inventory_event_zone_id'))
    )
    op.create_index(op.f('ix_inventory_event_id'), 'inventory', ['event_id'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'expired', 'cancelled', name='reservationstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_reservation_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_reservation_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('fk_reservation_inventory_id_inventory'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation'))
    )
    op.create_index(op.f('ix_reservation_inventory_id'), 'reservation', ['inventory_id'], unique=False)
    op.create_index('ix_reservation_pending_expires_at', 'reservation', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_reservation_user_id'), 'reservation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_user_id'), table_name='reservation')
    op.drop_index('ix_reservation_pending_expires_at', table_name='reservation', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_reservation_inventory_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_inventory_event_id'), table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
