# Generated by Django 6.1.1 on 2026-10-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxmessage",
            name="trace_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
