"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from config.logging import configure_logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "accounts",
    "events",
    "messaging",
]

MIDDLEWARE = [
    # First: the request id must exist before anything else logs.
    "config.middleware.RequestContextMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # Serves the admin's static files in containers (no separate web server).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["CATALOG_DB_NAME"],
        "USER": os.environ["CATALOG_DB_USER"],
        "PASSWORD": os.environ["CATALOG_DB_PASSWORD"],
        "HOST": os.environ.get("CATALOG_DB_HOST", "localhost"),
        "PORT": os.environ.get("CATALOG_DB_PORT", "5432"),
        # Each request is one transaction: a change and its outbox message are
        # saved together or not at all (see messaging/).
        "ATOMIC_REQUESTS": True,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # filled by `collectstatic` (Dockerfile)
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Behind the gateway, the admin form posts from http://localhost:8080.
CSRF_TRUSTED_ORIGINS = [
    origin
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django REST Framework

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # API clients send "Authorization: Bearer <token>".
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Lets the browsable API work when you're logged in to the admin.
        "rest_framework.authentication.SessionAuthentication",
    ],
    # Secure by default: every endpoint requires login unless the view opts out.
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # How many proxies sit in front of us. Throttling keys on the client IP; by
    # default DRF trusts the X-Forwarded-For header *the client sends*, so an
    # attacker could invent a new IP per login attempt and dodge the limit.
    # 0 = use the TCP peer address (local dev); 1 = behind our gateway, which
    # overwrites X-Forwarded-For with the real client IP.
    "NUM_PROXIES": int(os.environ.get("NUM_PROXIES", "0")),
    # Used by views that set `throttle_scope` (see accounts/views.py).
    "DEFAULT_THROTTLE_RATES": {
        "login": "5/min",  # brute-force protection, per client IP
        "register": "10/hour",
    },
}

# RabbitMQ: domain events for other services (published by `manage.py relay_outbox`).
RABBITMQ_URL = os.environ["RABBITMQ_URL"]
CATALOG_EVENTS_EXCHANGE = "catalog.events"

# Shared by every copy of the service, so throttling counters are global.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ["CATALOG_REDIS_URL"],
    }
}

SIMPLE_JWT = {
    # Own key, not SECRET_KEY: it will be shared with the booking service.
    "SIGNING_KEY": os.environ["JWT_SIGNING_KEY"],
    "ALGORITHM": "HS256",
    # Short-lived access token; the refresh token gets a new one without re-login.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "TicketHub Catalog API",
    "DESCRIPTION": "Public catalog of events, venues and prices.",
    "VERSION": "0.1.0",
}


# Logging: structlog for everything (see config/logging.py), not Django's default.
LOGGING_CONFIG = None
configure_logging(
    level=os.environ.get("LOG_LEVEL", "INFO"),
    fmt="json" if os.environ.get("LOG_FORMAT") == "json" else "console",
)
